
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS nav_links JSONB,
  ADD COLUMN IF NOT EXISTS services_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS services_title TEXT,
  ADD COLUMN IF NOT EXISTS services_subtitle TEXT,
  ADD COLUMN IF NOT EXISTS services JSONB,
  ADD COLUMN IF NOT EXISTS why_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS why_title TEXT,
  ADD COLUMN IF NOT EXISTS why_reasons JSONB,
  ADD COLUMN IF NOT EXISTS testimonials_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS testimonials_title TEXT,
  ADD COLUMN IF NOT EXISTS testimonials JSONB,
  ADD COLUMN IF NOT EXISTS catalog_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS catalog_title TEXT,
  ADD COLUMN IF NOT EXISTS contact_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS contact_title TEXT,
  ADD COLUMN IF NOT EXISTS contact_subtitle TEXT,
  ADD COLUMN IF NOT EXISTS contact_map_embed TEXT,
  ADD COLUMN IF NOT EXISTS contact_map_url TEXT,
  ADD COLUMN IF NOT EXISTS footer_description TEXT,
  ADD COLUMN IF NOT EXISTS footer_copyright TEXT,
  ADD COLUMN IF NOT EXISTS about_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS about_stat4_value TEXT,
  ADD COLUMN IF NOT EXISTS about_stat4_label TEXT,
  ADD COLUMN IF NOT EXISTS seo_home_title TEXT,
  ADD COLUMN IF NOT EXISTS seo_home_description TEXT,
  ADD COLUMN IF NOT EXISTS seo_home_keywords TEXT;
